USE [master]
GO
/****** Object:  Database [Ejercicio 4 DER]    Script Date: 18/6/2025 15:23:11 ******/
CREATE DATABASE [Ejercicio 4 DER]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ejercicio 4 DER', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Ejercicio 4 DER.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ejercicio 4 DER_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Ejercicio 4 DER_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Ejercicio 4 DER] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ejercicio 4 DER].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ejercicio 4 DER] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ejercicio 4 DER] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ejercicio 4 DER] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ejercicio 4 DER] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ejercicio 4 DER] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Ejercicio 4 DER] SET  MULTI_USER 
GO
ALTER DATABASE [Ejercicio 4 DER] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ejercicio 4 DER] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ejercicio 4 DER] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ejercicio 4 DER] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ejercicio 4 DER] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ejercicio 4 DER] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Ejercicio 4 DER] SET QUERY_STORE = ON
GO
ALTER DATABASE [Ejercicio 4 DER] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Ejercicio 4 DER]
GO
/****** Object:  Table [dbo].[Area]    Script Date: 18/6/2025 15:23:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Area](
	[cod_Area] [varchar](6) NOT NULL,
	[descripcion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Area] PRIMARY KEY CLUSTERED 
(
	[cod_Area] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Carretera]    Script Date: 18/6/2025 15:23:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Carretera](
	[cod_Carretera] [varchar](6) NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[tipo] [varchar](15) NOT NULL,
 CONSTRAINT [PK__Carreter__09A495F701239F8F] PRIMARY KEY CLUSTERED 
(
	[cod_Carretera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Municipalidades]    Script Date: 18/6/2025 15:23:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Municipalidades](
	[cod_Municipalidad] [varchar](6) NOT NULL,
	[cod_Tramo] [varchar](6) NOT NULL,
	[cod_Carretera] [varchar](6) NOT NULL,
	[nombre] [varchar](15) NOT NULL,
	[descripcion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Municipalidades] PRIMARY KEY CLUSTERED 
(
	[cod_Municipalidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tramo]    Script Date: 18/6/2025 15:23:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tramo](
	[cod_Tramo] [varchar](6) NOT NULL,
	[cod_Carretera] [varchar](6) NOT NULL,
	[cod_Area] [varchar](6) NOT NULL,
	[KMInicio] [int] NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Longitud] [int] NOT NULL,
	[KMFin] [int] NOT NULL,
 CONSTRAINT [PK_Tramo] PRIMARY KEY CLUSTERED 
(
	[cod_Tramo] ASC,
	[cod_Carretera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Tramo]    Script Date: 18/6/2025 15:23:11 ******/
CREATE NONCLUSTERED INDEX [IX_Tramo] ON [dbo].[Tramo]
(
	[cod_Tramo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Municipalidades]  WITH CHECK ADD  CONSTRAINT [FK_Municipalidades_Tramo] FOREIGN KEY([cod_Tramo], [cod_Carretera])
REFERENCES [dbo].[Tramo] ([cod_Tramo], [cod_Carretera])
GO
ALTER TABLE [dbo].[Municipalidades] CHECK CONSTRAINT [FK_Municipalidades_Tramo]
GO
ALTER TABLE [dbo].[Tramo]  WITH CHECK ADD  CONSTRAINT [FK_Tramo_Area] FOREIGN KEY([cod_Area])
REFERENCES [dbo].[Area] ([cod_Area])
GO
ALTER TABLE [dbo].[Tramo] CHECK CONSTRAINT [FK_Tramo_Area]
GO
ALTER TABLE [dbo].[Tramo]  WITH CHECK ADD  CONSTRAINT [FK_Tramo_Carretera] FOREIGN KEY([cod_Carretera])
REFERENCES [dbo].[Carretera] ([cod_Carretera])
GO
ALTER TABLE [dbo].[Tramo] CHECK CONSTRAINT [FK_Tramo_Carretera]
GO
USE [master]
GO
ALTER DATABASE [Ejercicio 4 DER] SET  READ_WRITE 
GO
