USE [master]
GO
/****** Object:  Database [Ejercicio 1 DER]    Script Date: 18/6/2025 15:19:28 ******/
CREATE DATABASE [Ejercicio 1 DER]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Ejercicio 1 DER', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Ejercicio 1 DER.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Ejercicio 1 DER_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Ejercicio 1 DER_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Ejercicio 1 DER] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Ejercicio 1 DER].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Ejercicio 1 DER] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET ARITHABORT OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Ejercicio 1 DER] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Ejercicio 1 DER] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Ejercicio 1 DER] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Ejercicio 1 DER] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Ejercicio 1 DER] SET  MULTI_USER 
GO
ALTER DATABASE [Ejercicio 1 DER] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Ejercicio 1 DER] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Ejercicio 1 DER] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Ejercicio 1 DER] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Ejercicio 1 DER] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Ejercicio 1 DER] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Ejercicio 1 DER] SET QUERY_STORE = ON
GO
ALTER DATABASE [Ejercicio 1 DER] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Ejercicio 1 DER]
GO
/****** Object:  Table [dbo].[Agencia]    Script Date: 18/6/2025 15:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Agencia](
	[cod_Agencia] [varchar](6) NOT NULL,
	[NroAgencia] [int] NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
	[Calle] [varchar](50) NOT NULL,
	[Nro] [int] NOT NULL,
 CONSTRAINT [PK_Agencia] PRIMARY KEY CLUSTERED 
(
	[cod_Agencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cliente]    Script Date: 18/6/2025 15:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cliente](
	[cod_Cliente] [varchar](6) NOT NULL,
	[DNI] [int] NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Apellido] [varchar](20) NOT NULL,
	[Telefono] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Cliente] PRIMARY KEY CLUSTERED 
(
	[cod_Cliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Coche]    Script Date: 18/6/2025 15:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Coche](
	[cod_Coche] [varchar](6) NOT NULL,
	[cod_Garaje] [varchar](6) NOT NULL,
	[Patente] [varchar](15) NOT NULL,
	[Modelo] [varchar](25) NOT NULL,
	[Marca] [varchar](25) NOT NULL,
 CONSTRAINT [PK_Coche] PRIMARY KEY CLUSTERED 
(
	[cod_Coche] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Garaje]    Script Date: 18/6/2025 15:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Garaje](
	[cod_Garaje] [varchar](6) NOT NULL,
	[NroGaraje] [int] NOT NULL,
	[Direccion] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Garaje] PRIMARY KEY CLUSTERED 
(
	[cod_Garaje] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reserva]    Script Date: 18/6/2025 15:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reserva](
	[cod_Reserva] [varchar](6) NOT NULL,
	[cod_Cliente] [varchar](6) NOT NULL,
	[cod_Agencia] [varchar](6) NOT NULL,
	[FechaInicio] [date] NOT NULL,
	[FechaFin] [date] NOT NULL,
 CONSTRAINT [PK_Reserva] PRIMARY KEY CLUSTERED 
(
	[cod_Reserva] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reserva_Coche]    Script Date: 18/6/2025 15:19:29 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reserva_Coche](
	[cod_Reserva] [varchar](6) NOT NULL,
	[cod_Coche] [varchar](6) NOT NULL,
 CONSTRAINT [PK_Reserva_Coche] PRIMARY KEY CLUSTERED 
(
	[cod_Reserva] ASC,
	[cod_Coche] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Coche]  WITH CHECK ADD  CONSTRAINT [FK_Coche_Garaje] FOREIGN KEY([cod_Garaje])
REFERENCES [dbo].[Garaje] ([cod_Garaje])
GO
ALTER TABLE [dbo].[Coche] CHECK CONSTRAINT [FK_Coche_Garaje]
GO
ALTER TABLE [dbo].[Reserva]  WITH CHECK ADD  CONSTRAINT [FK_Reserva_Agencia] FOREIGN KEY([cod_Agencia])
REFERENCES [dbo].[Agencia] ([cod_Agencia])
GO
ALTER TABLE [dbo].[Reserva] CHECK CONSTRAINT [FK_Reserva_Agencia]
GO
ALTER TABLE [dbo].[Reserva]  WITH CHECK ADD  CONSTRAINT [FK_Reserva_Cliente] FOREIGN KEY([cod_Cliente])
REFERENCES [dbo].[Cliente] ([cod_Cliente])
GO
ALTER TABLE [dbo].[Reserva] CHECK CONSTRAINT [FK_Reserva_Cliente]
GO
ALTER TABLE [dbo].[Reserva_Coche]  WITH CHECK ADD  CONSTRAINT [FK_Reserva_Coche_Coche] FOREIGN KEY([cod_Coche])
REFERENCES [dbo].[Coche] ([cod_Coche])
GO
ALTER TABLE [dbo].[Reserva_Coche] CHECK CONSTRAINT [FK_Reserva_Coche_Coche]
GO
ALTER TABLE [dbo].[Reserva_Coche]  WITH CHECK ADD  CONSTRAINT [FK_Reserva_Coche_Reserva] FOREIGN KEY([cod_Reserva])
REFERENCES [dbo].[Reserva] ([cod_Reserva])
GO
ALTER TABLE [dbo].[Reserva_Coche] CHECK CONSTRAINT [FK_Reserva_Coche_Reserva]
GO
USE [master]
GO
ALTER DATABASE [Ejercicio 1 DER] SET  READ_WRITE 
GO
